import type { NextPage } from 'next';
import NextHead from 'next/head';

const Head: NextPage = () => {
  return (
    <NextHead>
      <title>My Trading Card Database</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </NextHead>
  );
};

export default Head;
